/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#ffffff",
        ink: "#ffffff",
        body: "#bbbbbb",
        'body-strong': "#e6e6e6",
        muted: "#7e7e7e",
        hairline: "#3c3c3c",
        'hairline-strong': "#262626",
        canvas: "#000000",
        'surface-card': "#1a1a1a",
        'surface-elevated': "#262626",
        'surface-soft': "#0d0d0d",
        'on-primary': "#000000",
        'on-dark': "#ffffff",
        'm-blue-light': "#0066b1",
        'm-blue-dark': "#1c69d4",
        'm-red': "#e22718",
        'bmw-blue': "#1c69d4",
        'electric-blue': "#0653b6",
        'carbon-gray': "#2b2b2b",
        warning: "#f4b400",
        success: "#0fa336",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '1.05', fontWeight: '700' }],
        'display-md': ['40px', { lineHeight: '1.1', fontWeight: '700' }],
        'display-sm': ['32px', { lineHeight: '1.15', fontWeight: '700' }],
        'title-lg': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '400' }],
        'title-sm': ['18px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-uppercase': ['14px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '1.5px' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '300' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '300' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '400', letterSpacing: '0.5px' }],
        'button': ['14px', { lineHeight: '1', fontWeight: '700', letterSpacing: '1.5px' }],
        'nav-link': ['14px', { lineHeight: '1.4', fontWeight: '400', letterSpacing: '0.5px' }],
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'xxl': '64px',
        'section': '96px',
      },
      borderRadius: {
        'none': '0px',
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
